#!/bin/bash
# 快速推送脚本 - 需要 GitHub Personal Access Token
# Generated by Kai Digital Agent 🦞

set -e

REPO="wanyview/Matrix-BNUHS-v2"
BRANCH="main"
COMMIT_SHA=$(git rev-parse HEAD)

echo "🚀 Matrix-BNUHS-v2 V1.2 推送脚本"
echo ""
echo "📋 准备推送:"
echo "   仓库: $REPO"
echo "   分支: $BRANCH"
echo "   提交: $COMMIT_SHA"
echo ""

# 检查 token
if [ -z "$GITHUB_TOKEN" ]; then
    echo "⚠️  未设置 GITHUB_TOKEN 环境变量"
    echo ""
    echo "📝 请选择方式:"
    echo ""
    echo "方式 1: 设置环境变量后重试"
    echo "   export GITHUB_TOKEN=你的_token"
    echo "   $0"
    echo ""
    echo "方式 2: 输入 token (不安全，不推荐)"
    read -p "请输入 GitHub Personal Access Token: " TOKEN
    echo ""
else
    TOKEN=$GITHUB_TOKEN
fi

# 推送函数
push_to_github() {
    local token=$1
    local repo=$2
    local branch=$3
    local commit=$4

    echo "📤 推送中..."

    # 获取当前 ref
    local ref_response=$(curl -s -H "Authorization: token $token" \
        -H "Accept: application/vnd.github.v3.json" \
        "https://api.github.com/repos/$repo/git/refs/heads/$branch")

    local current_sha=$(echo $ref_response | grep -o '"sha":"[^"]*"' | head -1 | cut -d'"' -f4)

    if [ -z "$current_sha" ]; then
        echo "❌ 获取远程分支失败"
        echo "响应: $ref_response"
        return 1
    fi

    # 更新 ref
    local update_response=$(curl -s -X PATCH \
        -H "Authorization: token $token" \
        -H "Accept: application/vnd.github.v3.json" \
        -d "{\"sha\":\"$commit\",\"force\":true}" \
        "https://api.github.com/repos/$repo/git/refs/heads/$branch")

    echo "$update_response" | grep -q '"updated":'

    if [ $? -eq 0 ]; then
        echo ""
        echo "✅ 推送成功！"
        echo ""
        echo "📊 V1.2 升级内容:"
        echo "   • 环境上下文注入引擎 (ECIE)"
        echo "   • 模块化逻辑演化协议 (MLEP)"
        echo "   • 社交拓扑对齐模块 (STAM)"
        echo ""
        echo "🔗 查看代码: https://github.com/$repo/commit/$commit"
        return 0
    else
        echo "❌ 推送失败"
        echo "$update_response"
        return 1
    fi
}

# 执行推送
push_to_github "$TOKEN" "$REPO" "$BRANCH" "$COMMIT_SHA"
